services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-track-api
    restart: always
    ports:
      - '32001:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=10.0.2.2
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
